<?php
// +----------------------------------------------------------------------
// | CoreThink [ Simple Efficient Excellent ]
// +----------------------------------------------------------------------
// | Copyright (c) 2014 http://www.corethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: jry <598821125@qq.com> <http://www.corethink.cn>
// +----------------------------------------------------------------------
return array(
    'type'=>array(
        'title'=>'开启在线支付：',
        'type'=>'checkbox',
        'options'=>array(
            'Weixin'=>'Weixin',
            'Qq'=>'Qq',
            'Sina'=>'Sina',
            'Renren'=>'Renren',
        ),
    ),
    'group'=>array(
        'type'=>'group',
        'options'=>array(
            'Wexin'=>array(
                'title'=>'支付宝设置',
                'options'=>array(
                    'WeixinKEY'=>array(
                        'title'=>'收款账号邮箱：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weixin.qq.com/',
                    ),
                    'WeixinSecret'=>array(
                        'title'=>'加密key：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weixin.qq.com/',
                    ),
                    'WeixinSecret'=>array(
                        'title'=>'合作者ID：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weixin.qq.com/',
                    )
                )
            ),
            'Qq'=>array(
                'title'=>'财付通',
                'options'=>array(
                    'QqKEY'=>array(
                        'title'=>'QQ互联APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://connect.qq.com',
                    ),
                    'QqSecret'=>array(
                        'title'=>'QQ互联APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://connect.qq.com',
                    )
                ),
             ),
            'Sina'=>array(
                'title'=>'快线支付',
                'options'=>array(
                    'SinaKEY'=>array(
                        'title'=>'新浪APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weibo.com/',
                    ),
                    'SinaSecret'=>array(
                        'title'=>'新浪APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weibo.com/',
                    )
                ),
            ),
            'Renren'=>array(
                'title'=>'银联',
                'options'=>array(
                    'RenrenKEY'=>array(
                        'title'=>'人人APPKEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://dev.renren.com/',
                    ),
                    'RenrenSecret'=>array(
                        'title'=>'人人APPSECRET：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://dev.renren.com/',
                    )
                )
            )
        )
    )
);
